# Generated by Django 4.1.7 on 2023-03-29 10:44

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=10000)),
                ('image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('sub', models.CharField(max_length=250)),
            ],
        ),
    ]
