# Generated by Django 4.1.7 on 2023-04-03 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0002_rename_sub_blog_submit'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default=2, max_length=255),
            preserve_default=False,
        ),
    ]
