# Generated by Django 4.1.7 on 2023-04-03 10:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0005_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='branch',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='blog_app.branch'),
            preserve_default=False,
        ),
    ]
