# Generated by Django 4.1.7 on 2023-04-03 10:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0006_blog_branch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='branch',
            field=models.ForeignKey(default='Python', on_delete=django.db.models.deletion.CASCADE, to='blog_app.branch'),
        ),
    ]
