# Generated by Django 4.1.7 on 2023-04-06 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0007_alter_blog_branch'),
    ]

    operations = [
        migrations.CreateModel(
            name='contects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('mobile', models.ImageField(upload_to='')),
            ],
        ),
        migrations.AlterField(
            model_name='blog',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog_app.branch'),
        ),
    ]
