# Generated by Django 4.1.7 on 2023-04-06 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0008_contects_alter_blog_branch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contects',
            name='mobile',
            field=models.IntegerField(),
        ),
    ]
