# Generated by Django 4.1.7 on 2023-04-06 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0010_loginok'),
    ]

    operations = [
        migrations.DeleteModel(
            name='loginOK',
        ),
    ]
